"""empty message

Revision ID: 80b389866675
Revises: 8c23943911b6
Create Date: 2024-03-12 16:44:11.079425

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = '80b389866675'
down_revision = '8c23943911b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lat', sa.Numeric(scale=6, asdecimal=False), nullable=False))
        batch_op.add_column(sa.Column('lng', sa.Numeric(scale=6, asdecimal=False), nullable=False))

    if environment == "production":
      op.execute(f"ALTER TABLE vans SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vans', schema=None) as batch_op:
        batch_op.drop_column('lng')
        batch_op.drop_column('lat')

    # ### end Alembic commands ###
