"""empty message

Revision ID: e29fe6da2627
Revises: 89819aa5b7fb
Create Date: 2024-03-06 16:20:09.436560

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = 'e29fe6da2627'
down_revision = '89819aa5b7fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_van_favorite', ['user_id', 'van_id'])

    if environment == "production":
      op.execute(f"ALTER TABLE favorites SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['van_id'], ['id'])
        batch_op.drop_constraint('user_van_favorite', type_='unique')

    # ### end Alembic commands ###
