name: Node.js Build and Test CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: react-vite
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: react-vite/package-lock.json
        
    - name: Clean install dependencies
      run: |
        rm -rf node_modules
        npm install

    - name: Run Build
      run: npm run build:ci --if-present

    - name: Run Tests
      run: npm test --if-present
